version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: strongpassword
      POSTGRES_DB: openlab-database
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  openlab-backend:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: openlab-backend
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    restart: always

volumes:
  postgres-data:
